# -*- coding: utf-8 -*-
"""AV.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ac2to995-zrZeJ6JJjiLWeCHDLFY1c_K
"""

print("Bienvenido al asistente virtual Juanchito Cutuplay \n ¿Que deseas hacer?: \n 1)Deseo hacer una suma \n 2)Deseo hacer una resta \n 3)Deseo hacer una multiplicacion \n 4)Deseo hacer una division \n 4)Deseo imprimir mi nombre")
numero = int(input("Digite el numero: "))



def suma():
  cnt = int(input("Dijite la cantidad de numeros que desea sumar: "))
  c=0
  suma = 0
  while c < cnt:
    nm = float(input("Dijite el numero que va sumar: "))
    suma = suma + nm
    c= c+1
  print("El resultado es: ",suma)
def resta():
  cnt = int(input("Dijite la cantidad de numeros que desea restar: "))
  c=0
  resta = 0
  while c < cnt:
    nm = int(input("Dijite el numero que va restar: "))
    if c == 1:
      resta=nm
    elif c > 1:
      resta=resta/nm
    c = c+1
  print("El resultado es: ",resta)
def multiplicacion():
  cnt = int(input("Dijite la cantidad de numeros que desea multiplicar: "))
  c=0
  resta = 0
  while c < cnt:
    nm = int(input("Dijite el numero que va multiplicar: "))
    if c == 0 and nm>0:
      resta=nm
    elif c > 1 and nm>0:
      resta=resta/nm
    c = c+1
  print("El resultado es: ",resta)
def division():
  cnt = int(input("Dijite la cantidad de numeros que desea dividir: "))
  c=0
  resta = 0
  while c < cnt:
    nm = int(input("Dijite el numero que va dividir: "))
    if c == 0 and nm>0:
      resta=nm
    
    elif c > 1 and nm>0:
      resta=resta/nm
    c = c+1
    while nm == 0:
      print("Error division by zero")
      nm = int(input("Dijite el numero que va dividir: "))
    
  print("El resultado es: ",resta) 

def impresion():
  nombre = str(input("Digite su nombre: "))
  print(nombre)

if numero == 1:
  suma()
elif numero == 2:
  resta()
elif numero == 3:
  multiplicacion()
elif numero == 4:
  division()
elif numero == 5:
  impresion()
else:
  print("ERROR")